### ISSUE TITLE
need to create Github actions workflow specially  for windows build

### ISSUE THREAD

**Issue by khumnath** [khumnath/nepdate#3]
I attempted to set up a GitHub workflow to automatically build  Nepdate project, but unfortunately, I encountered errors. If anyone could create a workflow file that builds for both Linux and Windows, I would greatly appreciate the assistance. my failed workflow files can be seen in commit history.

**Comment by askaakura** [comment]
Hello. Thank you for the issue. Normally you are required to make a `.github` directory and `workflow.yaml` or `windows-build.yaml` or similar inside it, I can't found them. I can only see the failed jobs in actions. Last failed job suggest bad indentation in `yaml`. Please add those files so that I can review them. I have never built Qt app myself for desktop, but quick google searches show it as simple as using `make` command.

**Comment by khumnath** [comment]
I did created and tested workflows. You can check [https://github.com/khumnath/nepdate/tree/6a74ab953359c972b9c7b3c119d77e8bebf28045](here). I deleted workflow files from main branch

**Comment by khumnath** [comment]
@askaakura  can you fork repo and make workflow file for windows? linux is easy we can install default qt packages and build tools in github workspace, build there with cmake and publish with release.  For windows i manualy installed qt in windows 11 and built using qt creator and mingw kit in qtcreator. nepdate-calendar is working fine in windows. Still nepdate-widget is building but not displaying in windows.

**Comment by askaakura** [comment]
@khumnath I have been researching for a while yesterday on KDE repos. I got some lead, I will try to implement them today after work.

**Comment by khumnath** [comment]
found a way to build for windows. using qt creator i released windows application so auto build is not urgent now. i am closing this issue.   #9 
i released appimage too for linux.
release can be downloaded from https://github.com/khumnath/nepdate/releases/tag/v1.04
